name: Scheduled Ping

on:
  schedule:
    - cron: '*/2 * * * *'  # Chạy mỗi 1 phút
  workflow_dispatch:  # Cho phép chạy thủ công

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Health Check Server
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://pharmapoly-server.onrender.com/keep-alive
          follow-redirect: true
          max-attempts: 3
          retry-delay: 10s
